# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [ "usb_storage" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/1c9f11c5-629f-4a7f-bc09-118258472a7b";
    fsType = "btrfs";
    options = [ "subvol=@" ];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/1c9f11c5-629f-4a7f-bc09-118258472a7b";
    fsType = "btrfs";
    options = [ "subvol=@nix" ];
  };

  fileSystems."/var/cache" = {
    device = "/dev/disk/by-uuid/1c9f11c5-629f-4a7f-bc09-118258472a7b";
    fsType = "btrfs";
    options = [ "subvol=@cache" ];
  };

  fileSystems."/var/log" = {
    device = "/dev/disk/by-uuid/1c9f11c5-629f-4a7f-bc09-118258472a7b";
    fsType = "btrfs";
    options = [ "subvol=@log" ];
  };

  fileSystems."/swap" = {
    device = "/dev/disk/by-uuid/1c9f11c5-629f-4a7f-bc09-118258472a7b";
    fsType = "btrfs";
    options = [ "subvol=@swap" ];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/1c9f11c5-629f-4a7f-bc09-118258472a7b";
    fsType = "btrfs";
    options = [ "subvol=@home" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/BAEE-1EFC";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";
}
