# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [ ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/b5f6a6f7-d923-4a0e-b565-b913b5c1fb0e";
    fsType = "btrfs";
    options = [ "subvol=@" ];
  };

  fileSystems."/var/log" = {
    device = "/dev/disk/by-uuid/b5f6a6f7-d923-4a0e-b565-b913b5c1fb0e";
    fsType = "btrfs";
    options = [ "subvol=@log" ];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/b5f6a6f7-d923-4a0e-b565-b913b5c1fb0e";
    fsType = "btrfs";
    options = [ "subvol=@nix" ];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/b5f6a6f7-d923-4a0e-b565-b913b5c1fb0e";
    fsType = "btrfs";
    options = [ "subvol=@home" ];
  };

  fileSystems."/swap" = {
    device = "/dev/disk/by-uuid/b5f6a6f7-d923-4a0e-b565-b913b5c1fb0e";
    fsType = "btrfs";
    options = [ "subvol=@swap" ];
  };

  fileSystems."/var/cache" = {
    device = "/dev/disk/by-uuid/b5f6a6f7-d923-4a0e-b565-b913b5c1fb0e";
    fsType = "btrfs";
    options = [ "subvol=@cache" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/4A4A-1C01";
    fsType = "vfat";
    options = [
      "fmask=0177"
      "dmask=0077"
    ];
  };

  nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";
}
