# vim:ft=kitty

## name:     Catppuccin Kitty Diff Mocha
## author:   Catppuccin Org
## license:  MIT
## upstream: https://github.com/catppuccin/kitty/blob/main/themes/diff-mocha.conf
## blurb:    Soothing pastel theme for the high-spirited!

color_scheme light

# text
foreground           #cdd6f4
# base
background           #000000
# subtext0
title_fg             #a6adc8

# mantle
title_bg             #010101
margin_bg            #010101

# subtext1
margin_fg            #a6adc8
# mantle
filler_bg            #010101

# 30% red, 70% base
removed_bg           #492a33
# 50% red, 50% base
highlight_removed_bg #7a4654
# 40% red, 60% base
removed_margin_bg    #613843

# 30% green, 70% base
added_bg             #324531
# 50% green, 50% base
highlight_added_bg   #537251
# 40% green, 60% base
added_margin_bg      #425b40

# mantle
hunk_margin_bg       #010101
hunk_bg              #010101

# 40% yellow, 60% base
search_bg            #645a46
# text
search_fg            #cdd6f4
# 30% sky, 70% base
select_bg            #294247
# text
select_fg            #cdd6f4
