{
  flake.nixosModules.escapepod3-hardware =
    # Do not modify this file!  It was generated by ‘nixos-generate-config’
    # and may be overwritten by future invocations.  Please make changes
    # to /etc/nixos/configuration.nix instead.
    {
      config,
      lib,
      pkgs,
      modulesPath,
      ...
    }: {
      imports = [
        (modulesPath + "/installer/scan/not-detected.nix")
      ];
      boot.extraModulePackages = [];
      boot.initrd.availableKernelModules = ["usb_storage"];
      boot.initrd.kernelModules = [];
      boot.kernelModules = [];
      fileSystems."/" = {
        options = ["subvol=@"];
        device = "/dev/disk/by-uuid/1c9f11c5-629f-4a7f-bc09-118258472a7b";
        fsType = "btrfs";
      };
      fileSystems."/boot" = {
        options = [
          "fmask=0022"
          "dmask=0022"
        ];
        device = "/dev/disk/by-uuid/BAEE-1EFC";
        fsType = "vfat";
      };
      fileSystems."/home" = {
        options = ["subvol=@home"];
        device = "/dev/disk/by-uuid/1c9f11c5-629f-4a7f-bc09-118258472a7b";
        fsType = "btrfs";
      };
      fileSystems."/nix" = {
        options = ["subvol=@nix"];
        device = "/dev/disk/by-uuid/1c9f11c5-629f-4a7f-bc09-118258472a7b";
        fsType = "btrfs";
      };
      fileSystems."/swap" = {
        options = ["subvol=@swap"];
        device = "/dev/disk/by-uuid/1c9f11c5-629f-4a7f-bc09-118258472a7b";
        fsType = "btrfs";
      };
      fileSystems."/var/cache" = {
        options = ["subvol=@cache"];
        device = "/dev/disk/by-uuid/1c9f11c5-629f-4a7f-bc09-118258472a7b";
        fsType = "btrfs";
      };
      fileSystems."/var/log" = {
        options = ["subvol=@log"];
        device = "/dev/disk/by-uuid/1c9f11c5-629f-4a7f-bc09-118258472a7b";
        fsType = "btrfs";
      };
      nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";
      swapDevices = [];
    };
}
